spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/gymlearn
        username: YOUR_USERNAME
        password: YOUR_PASSWORD
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
